export = {
    whereami: "develop",
    "site": 'Group images',
    "url": 'http://localhost/',
    "mongoDB": 'mongodb://localhost/groupimages-dev',
    "redis_port": 6379,
    "app_port": 3000,
    "socket_port": 3001,
    "TOKEN_EXPIRATION": 60 * 24,
    "SALT_WORK_FACTOR": 10,
    "secretToken": 'aMdoeb5ed87zorRdkD6greDML81DcnrzeSD648ferFejmplx',
    'upload_dir': '/var/www/uploads/',
    'api_url': 'http://localhost:3000/',
    'debug': false,
    'response': { isError: false, text: "OK" },
}